excluded:
  - .build
  - Tests/Fixtures
  - Tests/AccessibilityTests/AccessibilityProject
  - Tests/XcodeTests/UIKitProject
  - Tests/XcodeTests/SwiftUIProject

opt_in_rules:
  - single_test_class

disabled_rules:
  # Formatting is handled by SwiftFormat
  - trailing_comma
  - opening_brace
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - indentation_width
  - attributes
  - anonymous_argument_in_multiline_closure
  - vertical_whitespace_between_cases

  # Length/size rules
  - cyclomatic_complexity
  - closure_body_length
  - function_body_length
  - type_body_length
  - file_length
  - line_length
  - identifier_name
  - type_name
  - large_tuple
  - function_parameter_count

  # Other
  - discouraged_optional_collection
  - non_optional_string_data_conversion # https://github.com/realm/SwiftLint/issues/5263#issuecomment-2115182747
  - balanced_xctest_lifecycle
  - todo
  - for_where
