#!/bin/bash

set -e

export DOCKER_CLI_HINTS=false
docker build -t periphery -f docker/Dockerfile.linux .
docker run --name periphery_write_linux_baseline -t periphery scan "$@" --write-baseline /linux.json
docker cp periphery_write_linux_baseline:linux.json ./baselines/linux.json
docker rm periphery_write_linux_baseline
